### ISSUE TITLE
Some maps have far away placed platform brushes

### ISSUE THREAD

**Issue by victorbstan** [gongpha/gdQmapbsp#15]
I've noticed that some maps spawn far away (bottom of map) platform brushes/entities like in the screenshots bellow. I will try to investigate why this is happening, but I figured I'd post it here if you might have an idea... 

<img width="1800" alt="Screenshot 2023-06-25 at 8 39 10 PM" src="https://github.com/gongpha/gdQmapbsp/assets/315297/f2384837-5bba-4bd0-87e2-4ed37a15dcd2">
<img width="1800" alt="Screenshot 2023-06-25 at 8 38 27 PM" src="https://github.com/gongpha/gdQmapbsp/assets/315297/fadcb094-5615-4654-9dc4-9f5c937e6548">
<img width="1800" alt="Screenshot 2023-06-25 at 8 38 00 PM" src="https://github.com/gongpha/gdQmapbsp/assets/315297/ec5584e4-d420-4b08-bb0c-bcce2a6e509a">

**Comment by gongpha** [comment]
Those brushes may be `func_plat`, which I haven't written their functionality to yet well enough. I'll fix it if I have time.

**Comment by victorbstan** [comment]
Should be fixed by: https://github.com/gongpha/gdQmapbsp/pull/13/commits/907ac1cc3d4bf5c2de397c7ef4727d06429a383e
