### ISSUE TITLE
Trains / Paths position/aabb wrong?

### ISSUE THREAD

**Issue by victorbstan** [gongpha/gdQmapbsp#24]
I've been trying to figure out why the two platforms in E1M3 have a gap between them. 
It seems as if the AABB is wrong, and/or the path origin is wrong and it spreads the platforms apart. 
<img width="1800" alt="Screenshot 2023-07-19 at 5 57 13 PM" src="https://github.com/gongpha/gdQmapbsp/assets/315297/ae2ddc11-0c35-4bd6-8b59-42878f062672">
<img width="1800" alt="Screenshot 2023-07-19 at 5 56 24 PM" src="https://github.com/gongpha/gdQmapbsp/assets/315297/00868403-5583-42af-9f7b-6f8f271e92bf">

**Comment by gongpha** [comment]
The current implementation uses AABB generated from Godot. I think it might be better to use bounds packed in the BSP file.
