### ISSUE TITLE
Some lightmap artifacts

### ISSUE THREAD

**Issue by victorbstan** [gongpha/gdQmapbsp#28]
Hi, I was testing some player merge work but noticed some lightmap artifacts, and I know there's been a very recent update to lightmaps, so I figured i'd let you know of a couple of places I saw some issues:

E3M1
<img width="1800" alt="Screenshot 2023-07-23 at 4 05 04 PM" src="https://github.com/gongpha/gdQmapbsp/assets/315297/329f9d44-d2a7-4713-a7ee-afbe3b6db9a3">

START
<img width="1800" alt="Screenshot 2023-07-23 at 4 04 13 PM" src="https://github.com/gongpha/gdQmapbsp/assets/315297/df7ed48b-692f-48f5-8db3-9343f3021f0d">

**Comment by gongpha** [comment]
Likely a regression from rebasing. I will do a quick fix.

**Comment by victorbstan** [comment]
Yeah, I gave up on rebasing a long time ago.... #alwaysmergegang 😼
