### ISSUE TITLE
Non animated textures/materials are black

### ISSUE THREAD

**Issue by victorbstan** [gongpha/gdQmapbsp#3]
Can load map now, but all textures that are not animated are completely black.

<img width="1648" alt="Screenshot 2023-06-16 at 7 16 21 AM" src="https://github.com/gongpha/gdQmapbsp/assets/315297/511d45c2-7b45-4b6c-8ae5-101d65ede0b1">
<img width="1800" alt="Screenshot 2023-06-16 at 7 17 42 AM" src="https://github.com/gongpha/gdQmapbsp/assets/315297/a6472dfb-a51a-4e25-b1b0-d7ce857419ca">

### Errors in log after running game:

<img width="1240" alt="Screenshot 2023-06-16 at 7 30 26 AM" src="https://github.com/gongpha/gdQmapbsp/assets/315297/bc074044-1d40-43a9-966c-4cd54bf2023a">

 Attached log file.

[godot.log](https://github.com/gongpha/gdQmapbsp/files/11769859/godot.log)

PS. Thanks for fixing the import issue.

**Comment by gongpha** [comment]
Looks like it's an engine rendering or platform-specific issue (MacOS).

Can you re-run the project with the project setting "Verbose Stdout" (`debug/settings/stdout/verbose_stdout`) enabled and resend a log here again please ?

I might figure out what was going on.

Or you can try finding related Godot issues here.
https://github.com/godotengine/godot/issues?q=label%3Aplatform%3Amacos+label%3Atopic%3Arendering

**Comment by victorbstan** [comment]
Good idea about verbose logging, I'm not yet very familiar with GD 4... I've attached the new log, seems like a shader issue, but could be an engine issue as well, I'm not sure. Thanks for looking into it... 
[godot.log](https://github.com/gongpha/gdQmapbsp/files/11773162/godot.log)

**Comment by gongpha** [comment]
I'm not sure if there's a limit on macOS's vulkan that caused the errors.

Try running this minimal project and check if this will get the same issue.
[i_47725dba2_001.zip](https://github.com/gongpha/gdQmapbsp/files/11776778/i_47725dba2_001.zip)

(This project just shows 256 noise textures at the center of the screen. Also, ignore the icon file error)

**Comment by victorbstan** [comment]
Hmm getting some errors logged but not sure if same issue? 
[godot.log](https://github.com/gongpha/gdQmapbsp/files/11777128/godot.log)
<img width="1793" alt="Screenshot 2023-06-16 at 7 33 45 PM" src="https://github.com/gongpha/gdQmapbsp/assets/315297/9b3e2a4e-1015-4f41-9ee9-efa36c99f7d1">

**Comment by victorbstan** [comment]
I guess I would wonder, what is it about the shaders you've shared that's different than the default meterials/shader that seems to work? 
<img width="1800" alt="Screenshot 2023-06-16 at 7 56 09 PM" src="https://github.com/gongpha/gdQmapbsp/assets/315297/33970a42-10d0-44ab-b5a8-90a42c2e8bc5">

**Comment by victorbstan** [comment]
I don't have a PC handy, but I'm curious if on your end, if you switch to "Mobile" rendering compatibility in the editor, does it still render properly?

**Comment by victorbstan** [comment]
`uniform sampler2D[256]` might be a problem...

**Comment by victorbstan** [comment]
This is probably not what you wanted to do, but this fades a noise texture to while... 

```glsl
shader_type spatial;
render_mode unshaded;

uniform sampler2D texs : source_color;

void fragment() {
	ALBEDO = texture(texs, UV).xyz * TIME * 4.0f;
}


```

**Comment by victorbstan** [comment]
So I went and commented out the `texs[256]` and changed them to just `texts` and this lol:

<img width="1800" alt="Screenshot 2023-06-16 at 10 02 19 PM" src="https://github.com/gongpha/gdQmapbsp/assets/315297/5cc66ce4-4f67-45ab-8385-ab9cb486ed0f">

**Comment by victorbstan** [comment]
Hmm, could this hint at the issue: https://stackoverflow.com/questions/45167538/error-sampler-arrays-indexed-with-non-constant-expressions-are-forbidden-in-gl 
```
The problem is that in line texColor = texture(textures[tid], fs_in.uv) the sampler array texturues is given a non constant index.
```

**Comment by gongpha** [comment]
> Hmm getting some errors logged but not sure if same issue? [godot.log](https://github.com/gongpha/gdQmapbsp/files/11777128/godot.log)

Likely.

> I guess I would wonder, what is it about the shaders you've shared that's different than the default meterials/shader that seems to work?

My shader has used a uniform array. This is what I have to test.

> Hmm, and if I switch the Godot renderer to Compatibility mode, it crashes the editor when trying to startup... hmm I thought Godot was for making cross platform games... :/ wonder what the funky parts of the custom shaders are that Vulkan to Metal translator can't deal with...

I got crashed either with Compatibility mode. (When opening the project in the editor). This seems an OpenGL issue.

> I don't have a PC handy, but I'm curious if on your end, if you switch to "Mobile" or "Compatibility" rendering mode in the editor, does it still render properly?

Yes, in Mobile. But not for Compatibility. T^T

> `uniform sampler2D[256]` might be a problem...
> 
> A non indexed sampler2D works (I can see noise texture):

Yes, but you might see only one single noise texture.

This is what it will show properly if nothing occurs.

https://github.com/gongpha/gdQmapbsp/assets/13400398/a6a20600-bb18-49db-aab8-1cb62b5b6bed

> 
> Edit 2:
> 
> either `sampler2D texs[256`] or `sampler2D[256] texs` seem to indicate that texs is an array of texture values (which are unassigned). And the `% 256` part might want to be `% 255`?

`% 256` is already correct. Since the size of the array is 256. The index value should wrap around 0 to 255.


> This is probably not what you wanted to do, but this fades a noise texture to white...

Yeah, The shader code you've modified is trying to multiply the time value to color fragments instead of trying to access the different noise textures by the time value

> Edit (disregard this comment):
> 
> So I suspect there might be something hardware specific/non-standard in some of the shader code, which is why it's not rendering properly (to go back to the original post) -- maybe there's a way to rewrite it to keep in mind some lower-common-denominator / wider compatibility shader features?

Yes, but before I will do that. I must figure out what the problem really is.

> Edit 2:
> 
> I'm less inclined to think that `texs[texidx]` is the problem... still investigating...

I think about that either. The uniform arrays are like there's a kind of hardware-specific work inside them . . .

**Comment by gongpha** [comment]
Can you try changing all the `256` numbers in both script code and shader code to anything lower (e.g. 64, 32) then re-run the project again ?

It seems like there are 2 possible problems. The limitation of textures (256) or accessing index by using non-constant value.

SO, The workaround is we've to change from a single material (of the whole level) to texture-dependent material.

Anyways, don't forget to report this issue or find the duplicate one on Godot (https://github.com/godotengine/godot/issues/new/choose). This issue shouldn't be occurred and can be considered as a bug. And you can also use my above minimal project as an MRP.

**Comment by victorbstan** [comment]
Not sure if this is good news or bad news. but changing the limit to `64` works! 
<img width="1800" alt="Screenshot 2023-06-17 at 9 04 21 PM" src="https://github.com/gongpha/gdQmapbsp/assets/315297/b978cd70-12f1-4364-ac1d-9ed719dfe41d">

**Comment by victorbstan** [comment]
> SO, The workaround is we've to change from a single material (of the whole level) to texture-dependent material.

This would seem more future proof, and less hacky TBH...

**Comment by victorbstan** [comment]
96 Seems to be the upper limit in the sampler 2D index.

**Comment by victorbstan** [comment]
Files a bug here: https://github.com/godotengine/godot/issues/78405

**Comment by gongpha** [comment]
> Not sure if this is good news or bad news. but changing the limit to `64` works!
> However, the lightmap seems off... (I'll make a new issue for that, just in case you are bored :P )

Maybe the unmatched array size made the shader goes buggy.

As a workaround, Try to add this code in `res://addons/qmapbsp/importer/bsp_parser.gd`, Line 663
```gdscript
global_textures.resize(64)
```
before `global_surface_mat.set_shader_parameter(&'texs', global_textures)` line.

**Comment by victorbstan** [comment]
That does fix it `global_textures.resize(GLOBAL_TEXTURE_LIMIT)`; but also, setting the limit to 96, I haven't seen any issues in any of the quake 1 maps anymore

**Comment by victorbstan** [comment]
Will close as initial issue was clarified and resolved. Thanks! :)
