### ISSUE TITLE
discord?

### ISSUE THREAD

**Issue by MissLavender-LQ** [gongpha/gdQmapbsp#35]
was wondering if yall had a discord wanted to see if i could play around with the quake 1 in godot yall had on YT 
see if i could try loading librequake with it n just general messing around with it before yall make it fully public 
my discord tag is [misslavender_lq] 
and my discord server is https://discord.gg/q3UvFRa8sU

**Comment by gongpha** [comment]
Here's the honest reason. I have bonded some stuff with the ID1 content for handy debugging and for sure I couldn't let them be released. I may return to fix these asap.

And about Discord, I've entered your server. My username is just the same as at Github.
