### ISSUE TITLE
Question about trenchbroom example and lightmaps

### ISSUE THREAD

**Issue by whussgit** [gongpha/gdQmapbsp#36]
Hello, I'm trying to import .MAP files in Godot, but I have some errors

Firstly, after setting up the game-configs and when I click on reimport i get the error "CANNOT_OPEN_BSP_FILE". I checked the path to qbsp in usercfg and it was correct.
Secondly, if I compile the map manually and put .bsp in the ".godot\qmapbsp\artifact" folder, after reimport it finally works correctly, but I get a scene with a standard material without lightmaps.

So, what should I do to get a full map scene with a quake shader included in it as in the quake1_template example?
I want to use your addon because it can import lightmaps from BSP format, this is a very important function!

**Comment by gongpha** [comment]
Have you set the "Game Config Path" property in the import inspector yet? (Or set them in "Import Defaults" in the project settings) If it doesn't fix the issue, Please send me an MRP (a Godot project that reproduces the problem, with no unnecessary files included). I will try to troubleshoot this.

And, the lightmap support in this addon is *currently only* supported in the Quake1 example part and works for BSP textures only (embed texture data in BSP files). But it can be ported to the Trenchbroom part easily.

Note that the lightmap support covers rendering animated lightmaps, and requires specific shader code. You may not use other materials arbitrarily.
